#!/bin/bash
# MENU CONTENT HELPER

#M00S=("$MI00_01" "$MI00_02" "$MI00_03" "$MI00_04" "$MI00_05" "$MI00_06" "$MI00_07" false "$MT00")


#PAGES
   #GREETING
   GP01="HELLO! THIS IS MY BASH HELPER APP!"
   GP02="IT WILL HELP YOU TO DO LOTS OF BORING STUFF!"
   GP03="LET'S GET STARTED!"

   #IN DEVELOPMENT
   ID01="UNFORTUNATELY THIS ACTION IS NOT AVAILABLE"
   ID02="THIS FEATURE IS IN DEVELOPMENT!"
   ID03="PREVIOUS MENU WILL BE LOADED IN 2 SECONDS"

   #WRONG SELECTION\
   WS01="IS A WRONG SELECTION"
   WS02="PLEASE SELECT ANOTHER ACTION!"
   WS03="PREVIOUS MENU WILL BE LOADED IN 2 SECONDS"

   #LAST PAGE
   LP01="THANS FOR USING THIS APP!"
   LP02="APP WILL BE CLOSED IN 2 SECONDS"
   LP03="SEE YOU SOON!"






#MAIN MENU
MT00="MAIN MENU"
MI00_01="SETUP A NEW UBUNTU/LINUX MINT SERVER"
MI00_02="THIS IS JUST A PLACEHOLDER FOR A MENU ITEM"
MI00_03="SETUP A NEW UBUNTU/LINUX MINT SERVER"
MI00_04="SETUP A NEW UBUNTU/LINUX MINT SERVER"
MI00_05="SETUP A NEW UBUNTU/LINUX MINT SERVER"
MI00_06="SETUP A NEW UBUNTU/LINUX MINT SERVER"
MI00_07="SETUP A NEW UBUNTU/LINUX MINT SERVER"
MI00_08="SETUP A NEW UBUNTU/LINUX MINT SERVER"
